---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Ansible Automation Platform インタラクティブラボへようこそ"
      solveButton: false
    - name: module-02
      label: "ラボガイド: Automation Controller 入門"
      solveButton: false
    - name: module-03
      label: "ラボガイド: Inventory の作成"
      solveButton: true
    - name: module-04
      label: "ラボガイド: 最初の Project を作成する"
      solveButton: true
    - name: module-05
      label: "ラボガイド: Credentials を理解する"
      solveButton: true
    - name: module-06
      label: "ラボガイド: Job Template の作成"
      solveButton: true
    - name: module-07
      label: "ラボガイド: 2つ目の Project を作成する"
      solveButton: true
    - name: module-08
      label: "ラボガイド: 複数の Job Template を作成する"
      solveButton: true
    - name: module-09
      label: "ラボガイド: Workflow Job Template の作成"
      solveButton: true
    - name: module-10
      label: "ラボガイド: Survey 付き Job Template の作成"
      solveButton: true


tabs:
  - name: Automation Controller
    url: https://control-${guid}.${domain}/
  - name: ">_ Terminal"
    url: /wetty


  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
